"""User: add session_token feild

Revision ID: 05ae1dd323ef
Revises: 1e0be764813e
Create Date: 2020-02-07 13:14:56.695283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ae1dd323ef'
down_revision = '1e0be764813e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('session_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_session_token'), 'user', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_token'), table_name='user')
    op.drop_column('user', 'session_token')
    # ### end Alembic commands ###
