"""add region and type feilds in Stock Table

Revision ID: 66439b6c3463
Revises: 05ae1dd323ef
Create Date: 2020-02-07 19:23:57.037465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66439b6c3463'
down_revision = '05ae1dd323ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('region', sa.String(length=20), nullable=True))
    op.add_column('stock', sa.Column('type', sa.String(length=25), nullable=True))
    op.create_unique_constraint(None, 'stock', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    op.drop_column('stock', 'type')
    op.drop_column('stock', 'region')
    # ### end Alembic commands ###
