"""add money feild in User Table

Revision ID: d8df2c0a9469
Revises: f88af909a85d
Create Date: 2020-02-08 02:07:18.141946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8df2c0a9469'
down_revision = 'f88af909a85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money', sa.Numeric(precision=13, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('money')

    # ### end Alembic commands ###
