"""empty message

Revision ID: f88af909a85d
Revises: 2183f96b7b0d
Create Date: 2020-02-07 19:48:21.387043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88af909a85d'
down_revision = '2183f96b7b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_stock_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_stock_symbol'), ['symbol'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_token'), ['session_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_token'))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_stock_symbol'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_stock_name'), type_='unique')

    # ### end Alembic commands ###
