"""empty message

Revision ID: fe91de780dc8
Revises: 66439b6c3463
Create Date: 2020-02-07 19:38:42.172768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe91de780dc8'
down_revision = '66439b6c3463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stock', ['name'])
    op.create_index(op.f('ix_user_session_token'), 'user', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_token'), table_name='user')
    op.drop_constraint(None, 'stock', type_='unique')
    # ### end Alembic commands ###
